<a href="https://colab.research.google.com/github/DayShad0w/py_DataScience/blob/HW%232/HW_2_%D0%9F%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Задание на повторение материала
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых 
чисел чисел от 12 до 24 невключительно



In [ ]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [ ]:
s = a.size
print(s)
a.shape = (3, 4)
print(a)
a.shape = (2,6)
print(a)
a1 = a.reshape([int(s/4), 4])
print(a1)
cols = 2
a2 = a.reshape([int(s/cols), cols])
print(a2)
a3 = a.reshape([2, 6])
print(a3)
a4 = a.reshape([3 ,4])
print(a4)
a5 = a.reshape([2 ,6])
print(a5)

12
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [ ]:
a1 = a.reshape([3,-1])
print(a1)
a2 = a.reshape([6,-1])
print(a2)
a3 = a.reshape([2,-1])
print(a3)
a4 = a.reshape([-1,4])
print(a4)
a5 = a.reshape([-1,6])
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [ ]:
# нельзя, так как обращение к элементам по одному индексу будет уже невозможно. Обязательно необходимо будет указать номер строки и номер столбца, хоть и номер столбца будет всегда одинаков.
# В памяти также будет занимать меньше места, нежели одномерный массив, при повторном "перевороте" размер одномерного массива будет меньше.
import sys
a = np.arange(0,12)
print(a)
print(sys.getsizeof(a))
b = a.reshape([12,1])
print(b)
print(sys.getsizeof(b))
c = b.reshape([12])
print(c)
print(sys.getsizeof(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
200
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
120
[ 0  1  2  3  4  5  6  7  8  9 10 11]
104


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [ ]:
b = np.random.randn(3,4)
b


array([[-0.44652555, -1.8074468 , -0.17084909,  0.7314408 ],
       [-0.74454769, -0.73380382,  0.90981135, -0.31638519],
       [-0.90941177, -0.16840271, -1.04384963, -0.57013883]])

In [ ]:
print(b.size)
b = b.flatten()
print(b.size)
b

12
12


array([-0.44652555, -1.8074468 , -0.17084909,  0.7314408 , -0.74454769,
       -0.73380382,  0.90981135, -0.31638519, -0.90941177, -0.16840271,
       -1.04384963, -0.57013883])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [ ]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [53]:
b = np.arange(20, 1, -2).reshape(1,10)
b
#различия в размерности матриц

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [ ]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a,b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
c.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [ ]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a = a.reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
At = a.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
b = np.dot(a, At)
b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [ ]:
b.size


16

In [ ]:
b.shape

(4, 4)

In [ ]:
inv=np.linalg.inv(b)
inv
# Ответ: raise LinAlgError("Singular matrix") Матрица вырожденная

LinAlgError: ignored

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [ ]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [ ]:
c = np.random.randint(0,16, 16)
c

array([11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [ ]:
print(c.size)
q = int(np.sqrt(c.size))
new = c.reshape(q, q)
new

16


array([[11,  9,  5, 12],
       [11,  8,  0, 10],
       [10, 14,  9, 15],
       [11, 11, 15, 14]])

In [ ]:
D = b + 10*new
D

array([[115, 104,  73, 152],
       [124, 130,  86, 222],
       [123, 226, 239, 362],
       [142, 232, 362, 442]])

In [ ]:
det = np.linalg.det(D)
print(det)
rank = np.linalg.matrix_rank(D)
print(rank)

62650800.0
4


In [ ]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01886552, -0.00325327, -0.01147599,  0.00454519],
       [ 0.01683203, -0.02439777,  0.02559361, -0.01449559],
       [ 0.01273886, -0.01565599, -0.00270994,  0.00570208],
       [-0.02532897,  0.02667356, -0.00752744,  0.00374073]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [ ]:
D_inv = np.where(D_inv<0, 0, 1)
D_inv

array([[1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
E = np.where(D_inv==1, b, new)
print(b)
print(new)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[11  9  5 12]
 [11  8  0 10]
 [10 14  9 15]
 [11 11 15 14]]


array([[  5,   9,   5,  32],
       [ 14,   8,  86,  10],
       [ 23,  14,   9, 212],
       [ 11, 122,  15, 302]])